-- REPASO PLSQL

-- TIPO RECORD
DECLARE
    company REGIONS%ROWTYPE;
    TYPE EMPRESA IS RECORD(
        nombre varchar2(100),
        lugar REGIONS%ROWTYPE
    );
    enterprise EMPRESA;
BEGIN
    enterprise.nombre := 'Gitbrave99';
    SELECT * INTO enterprise.lugar
    FROM REGIONS WHERE REGION_ID=4;
    DBMS_OUTPUT.PUT_LINE('enterprise: '||enterprise.nombre);
    DBMS_OUTPUT.PUT_LINE('region: '||enterprise.lugar.REGION_NAME);
END;

-- COLECCIONES
-- ARRAY ASOCIATIVO O INDEX BY TABLE
DECLARE
    TYPE DEPARTAMENTO IS TABLE OF
    VARCHAR(100)
    INDEX BY PLS_INTEGER;
    DEPARTAMENTOS DEPARTAMENTO;

    TYPE DEPART IS TABLE OF 
        REGIONS%ROWTYPE
    INDEX BY PLS_INTEGER;
    DEPARTS DEPART;
BEGIN
    DEPARTAMENTOS(1) := 'Santa Ana';
    SELECT * INTO DEPARTS(1)
    FROM REGIONS WHERE REGION_ID=4;

    DBMS_OUTPUT.PUT_LINE('region escalar: '||DEPARTAMENTOS(1));
    DBMS_OUTPUT.PUT_LINE('region rowtype: '||DEPARTS(1).REGION_NAME);
END;


-- COLECCIONES
-- VARRAYS
DECLARE
    --  TYPE V1 IS VARRAY(10) OF VARCHAR(100);
     TYPE EMPLEADO IS VARRAY(10) OF EMPLOYEES%ROWTYPE;
     EMPLEADOS EMPLEADO :=EMPLEADO();

BEGIN
    SELECT * BULK COLLECT INTO EMPLEADOS
    FROM EMPLOYEES WHERE ROWNUM <11;
    
    FOR I IN EMPLEADOS.FIRST()..EMPLEADOS.LAST() LOOP
        DBMS_OUTPUT.PUT_LINE('region rowtype: '||EMPLEADOS(I).FIRST_NAME);
    END LOOP;
    
END;
 

 -- COLECCIONES
-- NESTED TABLE
DECLARE
    TYPE EMPLEADO IS TABLE OF EMPLOYEES%ROWTYPE;
    EMPLEADOS EMPLEADO;
BEGIN
 
    DBMS_OUTPUT.PUT_LINE('region rowtype: '||EMPLEADOS(I).FIRST_NAME);
 
    
END;